  work-preview:
    description: |
      The work-preview is used on the homepage to display content for each case study preview.
    fields:
      - name: title
        type: string
        example: "Nature’s Care"
      - name: details-color
        type: string
        example: "natures-care"
      - name: details
        type: string
        example: "logo design / branding / stationery"
      - name: description
        type: string
        example: "Nature’s Care is a local health product shop"
      - name: data
        type: object
        data:
          source: "site.case-studies[0]"
          type: Project

  preview-img:
    description: |
      The preview-img is a preview image of the case study
    fields:
      - name: image
        type: image
        example: "natures-care-0.jpg"

  work-title:
    fields:
      - name: title
        type: string
        example: "Nature’s Care"
      - name: project-colour
        type: string
        example: "natures-care"
      - name: details
        type: string
        example: "logo design / brandng / stationery"

  work-about:
    description: |
      The work-about section is used for introducting project details on case study pages.
    fields:
      - name: title
        type: string
        example: "Nature’s Care"
      - name: details
        type: string
        example: "logo design / brandng / stationery"
        example: "Nature’s Care"
      - name: project-colour
        type: string
        example: "natures-care"
      - name: client
        type: string
        example: "Nature’s Care Health Products"
      - name: deliverables
        type: string
        example: "Logo Design, Branding, Stationery"
      - name: description
        type: string
        example: "Nature’s Care is a health product shop located in downtown Ottawa."
        data:
          source: "site.case-studies[0]"
          type: Project

  work-section:
    fields:
      - name: bg
        type: string
        example: "ideation"
      - name: heading
        type: string
        example: "ideation"
      - name: project-colour
        type: string
        example: "natures-care"

  ideation:
    fields:
      - name: image-i1
        type: image
        example: "natures-care-i1.jpg"
      - name: image-i2
        type: image
        example: "natures-care-i2.jpg"

  elements:
    fields:
      - name: image-e1
        type: image
        example: "natures-care-e1.jpg"
      - name: image-e2
        type: image
        example: "natures-care-e2.jpg"

  research:
    fields:
      - name: image-r1
        type: image
        example: "natures-care-r1.jpg"
      - name: image-r2
        type: image
        example: "natures-care-r2.jpg"

  image-full:
    fields:
      - name: image
        type: image
        example: "natures-care-3.jpg"
        data:
          source: "site.case-studies[0]"
          type: Project

  image-half:
    fields:
      - name: image
        type: image
        example: "natures-care-3.jpg"
        data:
          source: "site.case-studies[0]"
          type: Project

  project-nav:
    fields:
      - name: url-previous
        type: url
        example: "physicians-formula/"
      - name: color-previous
        type: string
        example: "nav-physicians-formula"
      - name: url-next
        type: url
        example: "mindu/"
      - name: color-next
        type: string
        example: "nav-mindu"
