patterns:
  basic:
    fields:
      - name: url
        type: url
        example: "/case-studies/natures-care/"
      - name: text
        type: text
        example: "view project"

  glow:
    fields:
      - name: url
        type: url
        example: "mailto:hello@treawnaharvey.ca"
      - name: text
        type: text
        example: say hello
      - name: target
        type: text
        example: "_blank"

  btn-work:
    fields:
      - name: url
        type: url
        example: "/case-studies/mindu/"
      - name: text-color
        type: string
        example: "btn-mindu"
      - name: btn-work-shadow
        type: string
        example: "btn-mindu-shadow"

  btn-next:
    fields:
      - name: url
        type: url
        example: "/case-studies/mindu/"
      - name: stroke-color
        type: string
        example: "#433cce"
